name: Deploy to S3 + CloudFront

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Python is available
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate sitemap.xml
        env:
          SITE_URL: ${{ vars.SITE_URL }}
        run: |
          python tools/generate_sitemap.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1


      - name: Sync site to S3
        run: |
          aws s3 sync . s3://gwsites-leweshomeconnect --delete \
            --exclude ".git/*" --exclude ".github/*" \
            --exclude "README.md" --exclude "LICENSE" \
            --exclude ".gitignore"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CF_DISTRIBUTION_ID }}" \
            --paths "/*"
